---
- hosts: web
  become: yes
  tasks:
    
    # Step 1: Install Docker and Docker Compose
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    # Step 2: Install NGINX
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    # Install Git
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install Composer using apt
      apt:
        name: composer
        state: present
        update_cache: yes

    - name: Add NGINX config for reverse proxy to Docker container on port 8080
      copy:
        dest: /etc/nginx/sites-available/yii2-app
        content: |
          server {
            listen 80;
            server_name _;

            location / {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
      notify:
        - Restart NGINX

    - name: Enable the yii2-app NGINX site
      file:
        src: /etc/nginx/sites-available/yii2-app
        dest: /etc/nginx/sites-enabled/yii2-app
        state: link
        force: yes

    - name: Enable NGINX site
      command: "ln -s /etc/nginx/sites-available/yii2-app /etc/nginx/sites-enabled/"
      args:
        creates: /etc/nginx/sites-enabled/yii2-app
      notify:
        - Restart NGINX

    # Test NGINX configuration
    - name: Test NGINX configuration
      command: nginx -t

    # (Optional) You don't need manual Restart here since notify will handle it
    # - name: Restart NGINX
    #   systemd:
    #     name: nginx
    #     state: restarted

    # Initialize Docker Swarm (if not already initialized)
    - name: Initialize Docker Swarm mode (if not initialized)
      command: docker swarm init
      ignore_errors: yes
      when: ansible_facts['distribution_version'] is version('18.04', '>=')

  handlers:
    - name: Restart NGINX
      systemd:
        name: nginx
        state: restarted